### ISSUE TITLE
Gliffy Macro - Can't edit diagram after conversion, clicking on the Edit page button

### ISSUE THREAD

**Issue by ane-gabriela** [xwikisas/xwiki-pro-macros#35]
Preconditions:

1. Create a new Gliffy in Confluence (eg. [Test Gliffy](https://xwikisas.atlassian.net/wiki/spaces/CT/pages/53870593/Test+Gliffy))
2. Export it as XML
3. Save the zip file on your device
4. Have xwiki-pro-macros 1.0-RC1 installed on the wiki instance used

Steps to reproduce:

1. Follow the steps from [Confluence to XWiki migration guide: from export to customization](https://xwiki.com/en/Blog/Confluence-to-XWiki-migration-export-import/)

Install Confluence XML module and File Streams Converter Application on your XWiki instance through the Extension Manager

After you have installed the two extensions, click on the Filter Stream Converter entry from the Applications panel:

- Choose the "Confluence XML input stream (confluence+xml)" input type
- Fill in the source field which contains "file:" followed by the path of the Confluence zip file, located on the machine where XWiki is running
- Add "gliffy" in the "Unprefixed macros"
- Choose the "XWiki instance output stream (xwiki+instance)" output type to import the Confluence pages in your wiki
- Click the "Convert" button

2. Navigate to the Home page (or any other page to refresh the pages)
3. From Navigation click on the newly created page
4. Click on the Convert button
5. Click on Edit 
![Edit](https://user-images.githubusercontent.com/40691112/112665951-4aef4280-8e64-11eb-9bd2-9962c21b8bc5.png)

Expected results: The diagram page opens in Edit mode > diagram can be edited (like any other diagram page). 

![AnyDiagram](https://user-images.githubusercontent.com/40691112/112666231-9f92bd80-8e64-11eb-8295-695a1b016aee.png)

Actual results: The page opens in edit mode showing the Gliffy macro

![ResultEdit](https://user-images.githubusercontent.com/40691112/112665942-46c32500-8e64-11eb-89ee-84e5c82d0304.png)

**_NOTE:_**
The Diagram is opened in Edit mode when clicking on the Edit pencil from the Diagram menu
![EditDiagram](https://user-images.githubusercontent.com/40691112/112666434-d9fc5a80-8e64-11eb-854e-b835beaaa1ea.png)

Environment: Windows 10, IE 11, XWiki 12.10.4 with MySQL 8.0 and xwiki-pro-macros 1.0-RC1

**Comment by oanat** [comment]
Tested locally with XWiki 11.10.11,  Filter Streams Converter Application  11.10.11 and  Confluence XML 9.11 and the conversion was ok for the same example.

**Comment by acotiuga** [comment]
@oanat  what about the Browser? Most of these problems are in IE.

**Comment by oanat** [comment]
@acotiuga You are right, I did not use IE for the test. I had a similar (functionally)  issue for a specific Gliffy diagram on Firefox but the one from this example worked. My issue was fixed by the upgrade of the Diagram application to the latest version. Maybe we should check if the same update has an effect on this ticket as well.

**Comment by ndascalita** [comment]
> If this works in current browsers, I believe we should close this issue.

Tested and could not replicate the issue with Pro Macros 1.14.2 on XWiki 14.10.16

**Comment by ane-gabriela** [comment]
@raphj Hello! I am still reproducing this issue with Chrome 124, Windows 11, XWiki Cloud 15.10.8, Pro Macros 1.16.5

![Step1 (2)](https://github.com/xwikisas/xwiki-pro-macros/assets/40691112/f4200b65-5c7d-4c88-bf9b-001a0e317fd3)

![Gliffy](https://github.com/xwikisas/xwiki-pro-macros/assets/40691112/42594b3b-459a-4c8d-aa8c-49c3c090a885)

**Comment by snazare** [comment]
This is the expected behaviour as a page in Confluence containing a Gliffy diagram will most likely contain other content, not only the diagram. Therefore, the "Edit" button clicked on imported page (with the Gliffy diagram converted into XWiki Diagram or not) will open page editing mode, not diagram editing. It is the same behaviour as the one obtained when one creates a diagram through the Diagram macro in XWiki:

<img width="823" alt="diagram-edit-page" src="https://github.com/user-attachments/assets/07377270-6549-4018-8121-4cbc51039fde">

or when an existing diagram is displayed on a page.
